Models/EF/Employer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJob.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.Evaluates = new HashSet<Evaluate>();
            this.Posts = new HashSet<Post>();
            this.Saves = new HashSet<Save>();
        }
    
        public long ID { get; set; }
        public string Fullname { get; set; }
        public string Place { get; set; }
        public string Image { get; set; }
        public string Descriptions { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluate> Evaluates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Save> Saves { get; set; }
    }
}

Areas/Admin/Controllers/EmployerController.cs
using FindJob.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindJob.Areas.Admin.Controllers
{
    public class EmployerController : Controller
    {
        private FindJobEntities db = new FindJobEntities();

        //show danh sách nhà tuyển dụng
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var model = db.Employers.OrderByDescending(x => x.Fullname).ToPagedList(page, pageSize);
            return View(model);
        }


        //Thay đổi trạng thái nhà tuyển dụng
        public JsonResult changeStatus(long ID)
        {
            var empl = db.Employers.Find(ID);
            var user = db.Users.Find(empl.User_ID);
            if (empl.Status == true)
            {
                user.Status = false;
                empl.Status = false;
            }
            else
            {
                user.Status = true;
                empl.Status = true;
            }
                
            db.SaveChanges();
            return Json(new
            {
                status = true
            });
        }

        //Autocomplete tìm kiếm nhà tuyển dụng
        public JsonResult ListName(string q)
        {
            var query = db.Employers.Where(x => x.Fullname.Contains(q)).Select(x => x.Fullname);
            return Json(new
            {
                data = query,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        //tìm kiếm  nhà tuyển dụng
        public ActionResult Search(string keyword, int page = 1, int pagesize = 6)
        {
            string[] key = keyword.Split(new string[] { " " }, StringSplitOptions.RemoveEmptyEntries);

            var empl_name = new List<Employer>();//Tìm theo tên sản phẩm
            foreach (var item in key)
            {
                empl_name = (from b in db.Employers
                             where b.Fullname.Contains(item)
                             select b).ToList();
            }
            ViewBag.KeyWord = keyword;
            return View(empl_name.ToPagedList(page, pagesize));
        }
    }
}

Controllers/EmployerController.cs
using FindJob.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace FindJob.Controllers
{
    public class EmployerController : Controller
    {
        private FindJobEntities db = new FindJobEntities();
        // GET: Employer
        // Hồ sơ nhà tuyển dụng
        public ActionResult Index(long ID)
        {
            var employer = db.Employers.FirstOrDefault(x => x.User_ID == ID);
            ViewBag.profile = employer;
            var sarary = db.Posts.Max(x => x.Salary);
            ViewBag.JobFeature = db.Posts.Where(x => x.Salary == sarary).ToList();
            if(employer != null)
            {
                ViewBag.ListEvaluate = db.Evaluates.Where(x => x.Type == 1 && x.Employer_ID == employer.ID).ToList();
            }
            return View();
        }


        //Chỉnh sửa hồ sơ nhà tuyển dụng
        public ActionResult Edit()
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");
            ViewBag.Employer = db.Employers.FirstOrDefault(x => x.User_ID == user.ID);
            return View();
        }


        //Lưu chỉnh sửa hồ sơ
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit_Employer(Employer entity, HttpPostedFileBase Image)
        {
            var employ = db.Employers.FirstOrDefault(x => x.User_ID == entity.User_ID);
            if (employ != null)
            {
                var emp = db.Employers.Find(entity.ID);
                emp.Fullname = entity.Fullname;
                emp.Place = entity.Place;
                emp.Descriptions = entity.Descriptions;
                emp.CompanyName = entity.CompanyName;
                emp.Address = entity.Address;
                emp.Email = entity.Email;
                emp.User_ID = entity.User_ID;
                emp.Status = true;
                if (Image != null && emp.Image != Image.FileName)
                {
                    //Xóa file cũ
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/Assets/images/employer"), emp.Image));
                    //Thêm hình ảnh
                    var path = Path.Combine(Server.MapPath("~/Assets/images/employer"), Image.FileName);
                    if (System.IO.File.Exists(path))
                    {
                        string extensionName = Path.GetExtension(Image.FileName);
                        string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                        path = Path.Combine(Server.MapPath("~/Assets/images/employer/"), filename);
                        Image.SaveAs(path);
                        emp.Image = filename;
                    }
                    else
                    {
                        Image.SaveAs(path);
                        emp.Image = Image.FileName;
                    }
                }
                db.SaveChanges();
            }
            else
            {
                //Thêm hình ảnh
                var path = Path.Combine(Server.MapPath("~/Assets/images/employer"), Image.FileName);
                if (System.IO.File.Exists(path))
                {
                    string extensionName = Path.GetExtension(Image.FileName);
                    string filename = Image.FileName + DateTime.Now.ToString("ddMMyyyy") + extensionName;
                    path = Path.Combine(Server.MapPath("~/Assets/images/employer/"), filename);
                    Image.SaveAs(path);
                    entity.Image = filename;
                }
                else
                {
                    Image.SaveAs(path);
                    entity.Image = Image.FileName;
                }

                db.Employers.Add(entity);
                db.SaveChanges();
            }
            var user = Session["user"] as User;
            return Redirect("/Employer/Index/" + user.ID);
        }

        //Đăng bài tuyển dụng
        public ActionResult Post()
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");
            ViewBag.Employer = db.Employers.FirstOrDefault(x => x.User_ID == user.ID);
            ViewBag.Career = db.Careers.ToList();
            return View();
        }


        //Lưu bài tuyển dụng
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddPost(Post entity)
        {
            entity.CreatedDate = DateTime.Now;
            entity.Status = true;
            db.Posts.Add(entity);
            db.SaveChanges();
            TempData["add_success"] = "Đăng thông tin tuyển dụng thành công";
            return RedirectToAction("Post");
        }

        //Sửa bài tuyển dụng
        public ActionResult EditPost(long ID)
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");
            ViewBag.Employer = db.Employers.FirstOrDefault(x => x.User_ID == user.ID);
            ViewBag.Career = db.Careers.ToList();
            ViewBag.Post = db.Posts.Find(ID);
            return View();
        }


        //Lưu chỉnh sửa
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit_Post(Post entity)
        {
            var post = db.Posts.Find(entity.ID);
            post.Title = entity.Title;
            post.Location = entity.Location;
            post.Career_ID = entity.Career_ID;
            post.Form = entity.Form;
            post.Dealine = entity.Dealine;
            post.Salary = entity.Salary;
            post.Descriptions = entity.Descriptions;
            post.Experience = entity.Experience;
            db.SaveChanges();
            TempData["add_success"] = "Sửa thông tin tuyển dụng thành công";
            return RedirectToAction("ListPost");
        }


        //Thêm đánh giá cho nhà tuyển dụng
        public JsonResult addEvaluate(string json_eval)
        {
            var JsonReview = new JavaScriptSerializer().Deserialize<List<Evaluate>>(json_eval);
            var eval = new Evaluate();
            foreach (var item in JsonReview)
            {
                eval.Candidate_ID = item.Candidate_ID;
                eval.Employer_ID = item.Employer_ID;
                eval.CreatedDate = DateTime.Now;
                eval.Rate = item.Rate;
                eval.Descriptions = item.Descriptions;
                eval.Type = 1;//Dùng cho người dùng đánh giá nhà tuyển dụng
                eval.Status = true;
            }

            db.Evaluates.Add(eval);
            db.SaveChanges();
            return Json(new
            {
                status = true
            });

        }


        //Bài tuyển dụng đã đăng
        public ActionResult ListPost(int page = 1, int pagesize = 10)
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");
            var employer = db.Employers.FirstOrDefault(x => x.User_ID == user.ID);
            if (employer == null)
                return RedirectToAction("Edit");
            var model = db.Posts.Where(x => x.Employer_ID == employer.ID).OrderByDescending(x => x.CreatedDate).ToPagedList(page, pagesize);
            return View(model);
        }


        //Danh sách ứng viên tham gia ứng tuyển
        public ActionResult ListJoin(long ID)
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");

            ViewBag.ListJoin = db.Joins.Where(x => x.Post_ID == ID && x.Status == false).ToList();
            ViewBag.Post = db.Posts.Find(ID);
            return View();
        }


        //Danh sách ứng viên đc chấp nhận
        public ActionResult Accept(long ID)
        {
            var user = Session["user"] as User;
            if (user == null)
                return Redirect("/User/Login");
            ViewBag.ListAccept = db.Joins.Where(x => x.Post_ID == ID && x.Status == true).ToList();
            ViewBag.Post = db.Posts.Find(ID);
            return View();
        }


        //Chọn ứng viên
        public JsonResult ChosesCandidate(long ID)
        {
            var join = db.Joins.Find(ID);
            join.Status = true;
            db.SaveChanges();
            return Json(new
            {
                status = true
            });

        }


        //XÓa ứng viên khỏi danh sách chấp nhận
        public JsonResult DeleteCandidate(long ID)
        {
            var join = db.Joins.Find(ID);
            join.Status = false;
            db.SaveChanges();
            return Json(new
            {
                status = true
            });

        }
        

        //Xóa bài viết
        public JsonResult DeletePost(long ID)
        {
            var join = db.Joins.Where(x => x.Post_ID == ID).ToList();
            foreach(var item in join)
            {
                db.Joins.Remove(item);
            }
            var save = db.Saves.Where(x => x.Post_ID == ID).ToList();
            foreach (var item in save)
            {
                db.Saves.Remove(item);
            }
            var post = db.Posts.Find(ID);
            db.Posts.Remove(post);
            db.SaveChanges();
            return Json(new
            {
                status = true
            });

        }
    }
}

Controllers/PostController.cs
using FindJob.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindJob.Controllers
{
    public class PostController : Controller
    {
        private FindJobEntities db = new FindJobEntities();
        // GET: Post
        public ActionResult Index()
        {
            return View();
        }

        //Chi tiết bài đăng
        public ActionResult Detail(long ID)
        {
            var model = db.Posts.Find(ID);
            ViewBag.post = model;
            ViewBag.Employer = db.Employers.Find(model.Employer_ID);
            ViewBag.Candidate = db.Candidates.ToList();
            return View();
        }


        //Tham gia ứng tuyển => đối với ứng viên
        public JsonResult JoinJob(long post_id, long candidate_id)
        {
            var res = db.Joins.Count(x => x.Post_ID == post_id && x.Candidate_ID == candidate_id);
            if(res == 0)
            {
                var join = new Join();
                join.Post_ID = post_id;
                join.Candidate_ID = candidate_id;
                join.DateJoin = DateTime.Now;
                join.Status = false;
                db.Joins.Add(join);
                db.SaveChanges();

                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
            
        }

        //Lưu công việc => đối với ứng viên
        public JsonResult SaveJob(long post_id, long candidate_id)
        {


            var res = db.Saves.Count(x => x.Post_ID == post_id && x.Candidate_ID == candidate_id);
            if (res == 0)
            {
                var save = new Save();
                save.Post_ID = post_id;
                save.Candidate_ID = candidate_id;
                save.DateSave = DateTime.Now;
                db.Saves.Add(save);
                db.SaveChanges();

                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        //Lưu nhà tuyển dụng => đối với ứng viên
        public JsonResult SaveEmployer(long employer_id, long candidate_id)
        {
            var res = db.Saves.Count(x => x.Employer_ID == employer_id && x.Candidate_ID == candidate_id);
            if (res == 0)
            {
                var save = new Save();
                save.Employer_ID = employer_id;
                save.Candidate_ID = candidate_id;
                save.DateSave = DateTime.Now;
                db.Saves.Add(save);
                db.SaveChanges();

                return Json(new
                {
                    status = true
                });
            }
            else
            {
                return Json(new
                {
                    status = false
                });
            }
                
        }
    }
}

Views/Employer/Accept.cshtml

@{
    ViewBag.Title = "Danh sách ứng viên được chọn";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int dem = 1;
    var listAccept = ViewBag.ListAccept as List<FindJob.Models.EF.Join>;
    var post = ViewBag.Post as FindJob.Models.EF.Post;
}


<section id="options" style="margin-top: 25px;">
    <div class="container">

        <!-- Columns Start -->
        <div class="row">
            <div class="col-sm-12">
                <h2>Danh sách ứng viên được chọn cho bài đăng: <span style="color: blue">@post.Title</span></h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Họ và tên ứng viên</th>
                                <th>Ngày ứng tuyển</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in listAccept)
                            {
                                <tr>
                                    <td>@dem</td>
                                    <td>@item.Candidate.Fullname</td>
                                    <td>@item.DateJoin.Value.ToString("hh:mm:ss tt dd/MM/yyyy")</td>
                                    <td>
                                        <a class="btn btn-default" href="/User/Profile_Candidate/@item.Candidate.User_ID" title="Xem thông tin ứng viên">Xem chi tiết</a>
                                        <button class="btn btn-danger btnDelete" data-id="@item.ID" title="Loại ứng viên">Loại ứng viên</button>
                                    </td>
                                </tr>
                                dem++;
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</section>


@section jsSection{

    <script>

        $(document).ready(function () {
            $('.btnDelete').click(function () {
                var ID = $(this).data("id");
                $.ajax({
                    data: {
                        ID: $(this).data("id")
                    },
                    url: '/Employer/DeleteCandidate',
                    dataType: 'Json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {

                            PNotify.success({
                                title: 'THÔNG BÁO!!',
                                text: 'Loại ứng viên thành công.'
                            });
                             setTimeout(function () {
                                window.location.href = "/Employer/Accept/" + @post.ID;
                            }, 5000);
                        }
                    }
                });
            });
        });

    </script>

}




Views/Employer/Edit.cshtml
@{
    ViewBag.Title = "Chỉnh sửa hồ sơ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = Session["user"] as FindJob.Models.EF.User;
    var employ = ViewBag.Employer as FindJob.Models.EF.Employer;
}

@if (employ != null)
{
    <section id="jobs" style="margin-top: 140px">
        <div class="container">
            @using (Html.BeginForm("Edit_Employer", "Employer", FormMethod.Post, new { enctype = "multipart/form-data" , id = "frmValidate"}))
            {
                <input type="hidden" name="User_ID" value="@user.ID" />
                <input type="hidden" name="ID" value="@employ.ID" />
                <div class="row">
                    <h2 class="text-center">Cập nhật thông tin nhà tuyển dụng</h2>
                    <div class="col-sm-6">
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Họ và tên</label>
                            <input type="text" class="form-control" value="@employ.Fullname" name="Fullname" id="job-email">
                        </div>
                        <div class="form-group" id="job-title-group">
                            <label for="job-title">Công ty tuyển dụng</label>
                            <input type="text" class="form-control" name="CompanyName" value="@employ.CompanyName" id="job-title">
                        </div>
                        <div class="form-group" id="job-location-group">
                            <label for="job-location">Số điện thoại</label>
                            <input type="text" class="form-control" name="Phone" value="@employ.Phone" id="job-title">
                        </div>
                        <div class="form-group wysiwyg" id="company-description-group">
                            <label>Giới thiệu nhà tuyển dụng</label>
                            <textarea rows="10" id="Descriptions" name="Descriptions">@employ.Descriptions</textarea>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Địa chỉ</label>
                            <input type="text" class="form-control" name="Address" value="@employ.Address" id="job-email">
                        </div>
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Địa điểm làm việc</label>
                            <input type="text" class="form-control" name="Place" value="@employ.Place" id="job-email">
                        </div>
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Email</label>
                            <input type="text" class="form-control" name="Email" id="job-email" value="@employ.Email.Trim()">
                        </div>
                        <div class="form-group" id="company-logo-group">
                            <label for="company-logo">Ảnh đại diện</label>
                            <label for="file-upload" class="custom-file-upload">
                                <i class="fa fa-cloud-upload"></i> @employ.Image
                            </label>
                            <input id="file-upload" name="Image" type="file" style="display:none;" accept="image/*">
                        </div>
                    </div>
                </div>
                <div class="row text-center">
                    <p>&nbsp;</p>
                    <button type="submit" href="#" class="btn btn-primary btn-lg">Chỉnh sửa hồ sơ </button>
                </div>
            }

        </div>
    </section>
}
else
{
    <section id="jobs" style="margin-top: 140px">
        <div class="container">
            @using (Html.BeginForm("Edit_Employer", "Employer", FormMethod.Post, new { enctype = "multipart/form-data" , id = "frmValidate"}))
            {
                <input type="hidden" name="User_ID" value="@user.ID" />
                <div class="row">
                    <h2 class="text-center">Thông tin nhà tuyển dụng</h2>
                    <div class="col-sm-6">
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Họ và tên</label>
                            <input type="text" class="form-control"  name="Fullname" id="job-email">
                        </div>
                        <div class="form-group" id="job-title-group">
                            <label for="job-title">Công ty tuyển dụng</label>
                            <input type="text" class="form-control" name="CompanyName" id="job-title">
                        </div>
                        <div class="form-group" id="job-location-group">
                            <label for="job-location">Số điện thoại</label>
                            <input type="text" class="form-control" name="Phone" id="job-title">
                        </div>
                        <div class="form-group wysiwyg" id="company-description-group">
                            <label>Giới thiệu nhà tuyển dụng</label>
                            <textarea rows="10" id="Descriptions" name="Descriptions"></textarea>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Địa chỉ</label>
                            <input type="text" class="form-control" name="Address" id="job-email">
                        </div>
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Địa điểm làm việc</label>
                            <input type="text" class="form-control" name="Place"id="job-email">
                        </div>
                        <div class="form-group" id="job-email-group">
                            <label for="job-email">Email</label>
                            <input type="text" class="form-control" name="Email" id="job-email">
                        </div>
                        <div class="form-group" id="company-logo-group">
                            <label for="company-logo">Ảnh đại diện</label>
                            <input  name="Image" type="file" accept="image/*">
                        </div>
                    </div>
                </div>
                <div class="row text-center">
                    <p>&nbsp;</p>
                    <button type="submit" href="#" class="btn btn-primary btn-lg">Chỉnh sửa hồ sơ </button>
                </div>
            }

        </div>
    </section>
}



@section jsSection{

    <script>

        $(document).ready(function () {
            CKEDITOR.replace('Descriptions');

             $(".datepicker").datepicker({
                format: "dd-mm-yyyy"
            });

            $('#file-upload').change(function () {
              var i = $(this).prev('label').clone();
              var file = '<i class="fa fa-cloud-upload"></i>' + $('#file-upload')[0].files[0].name;
              $(this).prev('label').empty();
              $(this).prev('label').append(file);
            });


            jQuery.validator.addMethod("phonenu", function (value, element) {
                if (/^(09[0-9]|07[0|6|7|8|9]|03[2-9]|08[1-5])+([0-9]{7})\b/g.test(value)) {
                    return true;
                } else {
                    return false;
                };
            }, "Invalid phone number");

            jQuery.validator.addMethod("email_regex", function (value, element) {
                if (/^[a-z][a-z0-9_\.]{5,32}@@[a-z0-9]{2,}(\.[a-z0-9]{2,4}){1,2}$/g.test(value)) {
                    return true;
                } else {
                    return false;
                };
            }, "Invalid email");
            //Khi bàn phím được nhấn và thả ra thì sẽ chạy phương thức này
            $("#frmValidate").validate({
                rules: {
                    Fullname: "required",
                    CompanyName: "required",
                    Image: "required",
                    Address: "required",
                    Descriptions: "required",
                    Email: {
                        required: true,
                        email_regex: true
                    },
                    Phone: {
                        required: true,
                        phonenu: true
                    }
                },
                messages: {
                    Fullname: "Vui lòng nhập họ và tên",
                    CompanyName: "Vui lòng nhập tên công ty tuyển dụng",
                    Image: "Vui lòng thêm ảnh",
                    Address: "Vui lòng nhập địa chỉ",
                    Descriptions: "Vui lòng nhập mô tả công ty tuyển dụng",
                    Email: {
                        required: "Vui lòng nhập email",
                        email_regex: "Email không hợp lệ"
                    },
                    Phone: {
                        required: "Vui lòng nhập số điện thoại",
                        phonenu: "Số điện thoại không hợp lệ"
                    }
                }
            });
        });

    </script>

}
