Models/EF/Career.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJob.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Career()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public long ID { get; set; }
        public string CareerName { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}

Areas/Admin/Controllers/CareerController.cs
using FindJob.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FindJob.Areas.Admin.Controllers
{
    public class CareerController : Controller
    {
        private FindJobEntities db = new FindJobEntities();
        // GET: Admin/Career
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var model = db.Careers.OrderByDescending(x => x.ID).ToPagedList(page, pageSize);
            return View(model);
        }


        public JsonResult Delete(long ID)
        {

            try
            {
                var career = db.Careers.Find(ID);
                db.Careers.Remove(career);
                db.SaveChanges();
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }

        }


        [HttpPost]
        public ActionResult addCareer(Career entity)
        {
            try
            {
                var prv = new Career();
                prv.CareerName = entity.CareerName;
                db.Careers.Add(prv);
                db.SaveChanges();
                TempData["add_success"] = "Thêm ngành tuyển dụng thành công";
                return RedirectToAction("Index");

            }
            catch
            {
                TempData["add_success"] = "Thêm ngành tuyển dụng KHÔNG thành công";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult editcareer(Career entity)
        {
            try
            {
                var prv = db.Careers.Find(entity.ID);
                prv.CareerName = entity.CareerName;
                db.SaveChanges();
                TempData["add_success"] = "Sửa ngành tuyển dụng thành công";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["add_success"] = "Sửa ngành tuyển dụng KHÔNG thành công";
                return RedirectToAction("Index");
            }
        }

        public JsonResult GetCareerByID(long ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var career = db.Careers.Find(ID);
            return Json(career, JsonRequestBehavior.AllowGet);
        }
    }
}

Areas/Admin/Views/Career/Index.cshtml

@{
    ViewBag.Title = "Ngành tuyển dụng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int dem = 1;
}
@model PagedList.IPagedList<FindJob.Models.EF.Career>
@using PagedList.Mvc



<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Quản lý ngành tuyển dụng</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            @if (TempData["add_success"] != null)
            {
                <div class="alert alert-success text-center text-uppercase" id="AlertBox">
                    @TempData["add_success"]
                </div>
            }
        </div>
        <div class="row">
            <div class="col-md-4" style="margin-bottom: 10px">
                <button class="btn btn-lg btn-primary" data-toggle="modal" data-target="#addCareer">Thêm mới </button>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="addCareer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Thêm mới ngành tuyển dụng</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("addCareer", "Career", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Tên ngành tuyển dụng:</label>
                                <input type="text" name="CareerName" class="form-control">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-lg">Thêm mới</button>
                            </div>
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        ngành tuyển dụng
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th class="text-center">Tên ngành tuyển dụng</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@dem</td>
                                            <td class="text-center">@item.CareerName</td>
                                            <td>
                                                <button class="btn btn-default btnEdit" data-id="@item.ID" title="Sửa ngành tuyển dụng"><i class="fa fa-edit"></i></button>
                                                <button class="btn btn-danger btnDelete" data-id="@item.ID" title="Xóa ngành tuyển dụng"><i class="fa fa-remove"></i></button>
                                            </td>
                                        </tr>
                                        dem++;
                                    }

                                </tbody>
                            </table>
                            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = Model.PageSize }))
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>

        </div>

    </div>
    <!-- /.container-fluid -->
</div>

<!-- Modal -->
<div class="modal fade editCareer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sửa ngành tuyển dụng</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("editCareer", "Career", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input type="hidden" name="ID" id="ID" />
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Tên ngành tuyển dụng:</label>
                        <input type="text" name="CareerName" id="CareerName" class="form-control">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Sửa</button>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

@section jsAdmin{

    <script type="text/javascript">
        $(function () {
            //nếu không có thao tác gì thì ẩn đi
            $('#AlertBox').removeClass('hide');

            //Sau khi hiển thị lên thì delay 1s và cuộn lên trên sử dụng slideup
            $('#AlertBox').delay(4000).slideUp(500);


            $('.btnDelete').off('click').on('click', function () {

                const notice = PNotify.notice({
                    title: 'Thông báo',
                    text: 'Bạn thật sự muốn xóa?',
                    icon: 'fa fa-question-circle',
                    width: '360px',
                    minHeight: '110px',
                    hide: false,
                    closer: false,
                    sticker: false,
                    destroy: true,
                    stack: new PNotify.Stack({
                        dir1: 'down',
                        modal: true,
                        firstpos1: 25,
                        overlayClose: false
                    }),
                    modules: new Map([
                        ...PNotify.defaultModules,
                        [PNotifyConfirm, {
                            confirm: true
                        }]
                    ])
                });

                notice.on('pnotify:confirm', () =>
                     $.ajax({
                        data: { ID: $(this).data('id') },
                        url: '/Admin/Career/Delete',
                        dataType: 'Json',
                        type: 'POST',
                        success: function (res) {
                            if (res.status == true) {
                                PNotify.success({
                                    title: 'THÔNG BÁO!!',
                                    text: 'Xóa ngành tuyển dụng thành công.'
                                });

                                 setTimeout(function () {
                                window.location.href = "/Admin/Career/Index";
                            }, 5000);
                            } else {
                                PNotify.error({
                                    title: 'THÔNG BÁO!!',
                                    text: 'Xóa ngành tuyển dụng KHÔNG thành công.'
                                });
                            }
                        }
                    })

                );
                //notice.on('pnotify:cancel', () => alert('Oh ok. Chicken, I see.'));




            });

            $('.btnEdit').click(function(event) {
                $('.editCareer').modal('show');
                //alert($(this).data('id'));
                var ID = $(this).data('id');
                $.ajax({
                        url: "/Admin/Career/GetCareerByID/" + ID,
                        type: 'GET',
                        dataType: 'json',
                        contentType: "application/json; charset=utf-8",
                        success: function (res) {
                            $('#CareerName').val(res.CareerName);
                            $('#ID').val(res.ID);
                        }
                    });
            });

        });
    </script>

}



